name: .NET - Build, test, and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Test
      run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - uses: actions/upload-artifact@v2
      with:
        name: artifact-codecoverage
        path: /Users/runner/work/Azure.Messaging.ServiceBus.Compression/Azure.Messaging.ServiceBus.Compression/test/Azure.Messaging.ServiceBus.Compression.Test/coverage.opencover.xml
        
    - name: Pack
      run: dotnet pack src/Azure.Messaging.ServiceBus.Compression/Azure.Messaging.ServiceBus.Compression.csproj -c Release --no-restore --no-build --include-symbols -p:SymbolPackageFormat=snupkg -o .
   
    - uses: actions/upload-artifact@v3
      with:
        name: artifact-nuget
        path: /Users/runner/work/Azure.Messaging.ServiceBus.Compression/Azure.Messaging.ServiceBus.Compression/*nupkg

    - name: Push to NuGet
      run: dotnet nuget push *.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
      
  
  upload-to-codecov:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact-codecoverage
      - name: Test artifact download
        run: ls -R
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
